### ISSUE TITLE
New problem - client crashes out of minecraft

### ISSUE THREAD

**Issue by djlawler** [triphora/emcutils#44]
1.20.4 client, fabric and fabricapi are up to date.
With the utilities unloaded I have no problem
With the utilities loaded, if I do /vault I get:
Probably just needs a check added??

java.lang.IllegalStateException: Not a JSON Object: ""
	at com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:101)
	at coffee.waffle.emcutils.feature.UsableItems.isUsableItemWithCooldown(UsableItems.java:52)
	at coffee.waffle.emcutils.feature.UsableItems.lambda$init$0(UsableItems.java:19)
	at coffee.waffle.emcutils.event.TooltipCallback.lambda$static$0(TooltipCallback.java:12)
	at coffee.waffle.emcutils.fabric.EMCUtilsFabric.lambda$onInitializeClient$0(EMCUtilsFabric.java:40)
	at net.fabricmc.fabric.api.client.item.v1.ItemTooltipCallback.lambda$static$0(ItemTooltipCallback.java:34)
	at net.minecraft.class_1799.handler$zjf000$fabric-item-api-v1$getTooltip(class_1799.java:2647)
	at net.minecraft.class_1799.method_7950(class_1799.java:823)
	at net.minecraft.class_437.method_25408(class_437.java:226)
	at net.minecraft.class_465.method_51454(class_465.java:187)
	at net.minecraft.class_465.method_2380(class_465.java:182)
	at coffee.waffle.emcutils.feature.VaultScreen.method_25394(VaultScreen.java:94)
	at net.minecraft.class_437.method_47413(class_437.java:110)
	at net.minecraft.class_757.mixinextras$bridge$method_47413$241(class_757.java)
	at net.minecraft.class_757.wrapOperation$bah000$fabric-screen-api-v1$onRenderScreen(class_757.java:2111)
	at net.minecraft.class_757.method_3192(class_757.java:931)
	at net.minecraft.class_310.method_1523(class_310.java:1327)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

**Comment by triphora** [comment]
fixed in 5a3174b5ced11264844cfc27b6b2cb97af5d55d9

**Comment by djlawler** [comment]
Thanks!
